# -*- mode: python ; coding: utf-8 -*-

a = Analysis(
    ['acr122u_bridge.py'],
    pathex=[],
    binaries=[],
    datas=[],
    hiddenimports=[
        'pystray._win32',
        'PIL',
        'smartcard',
        'smartcard.System',
        'smartcard.util',
        'smartcard.CardRequest',
        'smartcard.CardType',
        'smartcard.CardConnection',
        'smartcard.Exceptions',
        'smartcard.pcsc',
        'smartcard.pcsc.PCSCCardRequest',
        'smartcard.pcsc.PCSCCardConnection',
        'smartcard.scard',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='ACR122U_NFC',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=False,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)